### ISSUE TITLE
Field ID

### ISSUE THREAD

**Issue by Mickyc94** [Quackster/Kepler#144]
Im using IntelliJ IDEA to run the server and I manage to get on the server and enter public rooms but when it comes to creating a room I get the following error on the server.

`2018-07-26T22:05:18.933 ERROR [ErrorLogger] - Error when executing MySQL query: 
java.sql.SQLException: (conn=327) Field 'id' doesn't have a default value
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:198)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:110)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:228)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:216)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:150)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeUpdate(MariaDbPreparedStatementClient.java:183)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.alexdev.kepler.dao.mysql.NavigatorDao.createRoom(NavigatorDao.java:112)
	at org.alexdev.kepler.messages.incoming.rooms.settings.CREATEFLAT.handle(CREATEFLAT.java:66)
	at org.alexdev.kepler.messages.MessageHandler.invoke(MessageHandler.java:315)
	at org.alexdev.kepler.messages.MessageHandler.handleRequest(MessageHandler.java:302)
	at org.alexdev.kepler.server.netty.connections.ConnectionHandler.channelRead0(ConnectionHandler.java:73)
	at org.alexdev.kepler.server.netty.connections.ConnectionHandler.channelRead0(ConnectionHandler.java:18)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:546)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.sql.SQLException: Field 'id' doesn't have a default value
Query is: INSERT INTO rooms (owner_id, name, description, model, showname, password, accesstype) VALUES (?,?,?,?,?, '', ?), parameters [1,'Home','','model_a',1,0]
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:153)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:255)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:209)
	... 31 more`

I also cannot Update motto or buy furniture but im guessing it has something to do with the above error.

**Comment by Mickyc94** [comment]
It doesnt matter, fixed creating rooms, not sure about buying furni and changing motto though.

**Comment by Quackster** [comment]
Please import the database correctly, your import somehow missed this: 

https://github.com/Quackster/Kepler/blob/master/tools/kepler.sql#L1634

>Is changing motto and avatar clothes a CMS thing in V21 because I cannot remember?

Yes, there's a Dockerfile which will auto-install the server with the CMS etc, and it's kept up to date too.

**Comment by Mickyc94** [comment]
Thankyou for letting me know, not quite sure as I used the SQL that I downloaded with latest download but it didnt seem to set the AUTO INCREMENT but done it on the ones that needed doing before I saw this.
