### ISSUE TITLE
 problem with run.bat

### ISSUE THREAD

**Issue by lavalitaa4** [Quackster/Kepler#15]
hi, when i start the bat this appears:

"tile" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable. (_is not recognized as an internal or external command,
executable program or batch file_)

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/alexdev/k
epler/Kepler has been compiled by a more recent version of the Java Runtime (cla
ss file version 54.0), this version of the Java Runtime only recognizes class fi
le versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Presione una tecla para continuar . . .

I have the latest version of Java Runtime and java, my PC is Windows  8.1, why is this happening?

![Java error](https://user-images.githubusercontent.com/16296745/88075549-f2cea680-cb46-11ea-9a70-a22a7d4a242b.png)

Any tutorial?, i'm little confused with the files, and the instalations of programs

thanks

**Comment by emansom** [comment]
Install OpenJDK 12 from [here](https://developers.redhat.com/products/openjdk/download) ([direct link to installer](https://developers.redhat.com/download-manager/file/java-12-openjdk-12.0.1.12-1.windows.redhat.x86_64.msi)).

**Comment by lavalitaa4** [comment]
Sorry, the error continues and I get this too:
![error 2](https://user-images.githubusercontent.com/16296745/88320921-5514dc00-ccec-11ea-9afe-34217fe17500.png)

maybe it's because i have Windows 8,1?

**Comment by Quackster** [comment]
You aren't running the correct version of Java. Install Gradle and compile it yourself or install the correct Java runtime.
