### ISSUE TITLE
kepler.sql doesn't contain proper sound_set definitions, causes servers/items issues

### ISSUE THREAD

**Issue by rafaeldamasceno** [Quackster/Kepler#60]
First of all, it seems that the dump in kepler.sql isn't really kept up to date.

Because of this, I can't tell if this is an issue with outdated definitions or simply an error in the server. Here are two exception logs:

```
2018-07-06T23:10:34.279 ERROR [ErrorLogger] - Error occurred when handling (219):
java.lang.NullPointerException
	at org.alexdev.kepler.game.inventory.Inventory.getCasts(Inventory.java:54)
	at org.alexdev.kepler.game.inventory.Inventory.getView(Inventory.java:42)
	at org.alexdev.kepler.messages.incoming.songs.INSERT_SOUND_PACKAGE.handle(INSERT_SOUND_PACKAGE.java:70)
	at org.alexdev.kepler.messages.MessageHandler.invoke(MessageHandler.java:310)
	at org.alexdev.kepler.messages.MessageHandler.handleRequest(MessageHandler.java:297)
	at org.alexdev.kepler.server.netty.connections.ConnectionHandler.channelRead0(ConnectionHandler.java:65)
	at org.alexdev.kepler.server.netty.connections.ConnectionHandler.channelRead0(ConnectionHandler.java:16)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:547)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:501)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:844)
```
The one above happened when inserting the set into the Trax. The following happened when trying to open the hand after this:
```
2018-07-06T23:11:08.156 ERROR [ErrorLogger] - Error occurred when handling (65):
java.lang.NullPointerException
	at org.alexdev.kepler.game.inventory.Inventory.getCasts(Inventory.java:54)
	at org.alexdev.kepler.game.inventory.Inventory.getView(Inventory.java:42)
	at org.alexdev.kepler.messages.incoming.inventory.GETSTRIP.handle(GETSTRIP.java:11)
	at org.alexdev.kepler.messages.MessageHandler.invoke(MessageHandler.java:310)
	at org.alexdev.kepler.messages.MessageHandler.handleRequest(MessageHandler.java:297)
	at org.alexdev.kepler.server.netty.connections.ConnectionHandler.channelRead0(ConnectionHandler.java:65)
	at org.alexdev.kepler.server.netty.connections.ConnectionHandler.channelRead0(ConnectionHandler.java:16)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:547)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:501)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

The hand becomes unusable after this.

**Comment by Quackster** [comment]
Fixed: https://github.com/Quackster/Kepler/commit/f7786b78eefc1860685b9af568b491145049f957
