### ISSUE TITLE
libsodium fails to be loaded in Windows environments

### ISSUE THREAD

**Issue by rafaeldamasceno** [Quackster/Kepler#61]
When trying to login with a registered username (as an invalid one doesn't even try to match the password), I get the following exception:
```2018-07-12T18:33:45.520 ERROR [ErrorLogger] - Error when executing MySQL query: 
java.lang.IllegalArgumentException: The path has to be absolute (start with '/').
	at com.goterl.lazycode.lazysodium.utils.NativeUtils.loadLibraryFromJar(NativeUtils.java:62)
	at com.goterl.lazycode.lazysodium.SodiumJava.registerFromResources(SodiumJava.java:86)
	at com.goterl.lazycode.lazysodium.SodiumJava.<init>(SodiumJava.java:21)
	at org.alexdev.kepler.dao.mysql.PlayerDao.login(PlayerDao.java:118)
	at org.alexdev.kepler.messages.incoming.handshake.TRY_LOGIN.handle(TRY_LOGIN.java:16)
	at org.alexdev.kepler.messages.MessageHandler.invoke(MessageHandler.java:310)
	at org.alexdev.kepler.messages.MessageHandler.handleRequest(MessageHandler.java:297)
	at org.alexdev.kepler.server.netty.connections.ConnectionHandler.channelRead0(ConnectionHandler.java:65)
	at org.alexdev.kepler.server.netty.connections.ConnectionHandler.channelRead0(ConnectionHandler.java:16)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:146)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by rafaeldamasceno** [comment]
Fixed by the above PR.
