### ISSUE TITLE
Default running location in Gradle task causes file not found exception

### ISSUE THREAD

**Issue by rafaeldamasceno** [Quackster/Kepler#62]
By default, using the Gradle task run, Kepler is ran in `./Kepler/Kepler-Server/`. In this location, it tries to open the path `./tools/game_data/external_texts.txt`, which doesn't exist (it's one level up, rather).

Exception log:
```
2018-07-12T18:35:03.014 ERROR [ErrorLogger] - Error occurred when reading external_texts.txt:
java.nio.file.NoSuchFileException: tools/gamedata/external_texts.txt
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:215)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:369)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:415)
        at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.base/java.nio.file.Files.newInputStream(Files.java:154)
        at java.base/java.nio.file.Files.newBufferedReader(Files.java:2830)
        at org.alexdev.kepler.game.texts.TextsManager.readExternalTexts(TextsManager.java:31)
        at org.alexdev.kepler.game.texts.TextsManager.<init>(TextsManager.java:24)
        at org.alexdev.kepler.game.texts.TextsManager.getInstance(TextsManager.java:91)
        at org.alexdev.kepler.Kepler.main(Kepler.java:85)
```

**Comment by Quackster** [comment]
Not sure what IDE you're using but with IntellJ, which is what I use, it runs the project at the root folder, so all files and stuff are found by Kepler.

**Comment by rafaeldamasceno** [comment]
Gradle is IDE agnostic, and its tasks do the same in all of them. I'm specifically talking about the `gradle run` task which runs in `Kepler-Server` by default. Of course, if I create the .jar and run it from the project root, I get no issues as well, be it in IntelliJ or any other IDE/terminal.

**Comment by Quackster** [comment]
Move the files to the directory that's executing, and then gitignore it. Pretty simple solution.
